
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"